#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.4 on Wed Apr  5 13:12:55 2023
#
import subprocess

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((314, 189))
        self.SetTitle("Aplicativos Geoprocessamento")
        _icon = wx.NullIcon
        _icon.CopyFromBitmap(wx.Bitmap("assets/geo.ico", wx.BITMAP_TYPE_ANY))
        self.SetIcon(_icon)

        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)

        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, "O que deseja fazer?")
        label_1.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Segoe UI"))
        sizer_2.Add(label_1, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 2)

        self.PreRelatorio = wx.Button(self.panel_1, wx.ID_ANY, u"Relatório preliminar")
        sizer_2.Add(self.PreRelatorio, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 5)

        self.OrganizarLaudo = wx.Button(self.panel_1, wx.ID_ANY, "Organizar Laudo")
        sizer_2.Add(self.OrganizarLaudo, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 5)

        self.Certificacao = wx.Button(self.panel_1, wx.ID_ANY, u"Certificação")
        sizer_2.Add(self.Certificacao, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 5)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()
        # end wxGlade

        self.PreRelatorio.Bind(wx.EVT_BUTTON, self.on_pre_report)
        self.OrganizarLaudo.Bind(wx.EVT_BUTTON, self.on_laudo)
        self.Certificacao.Bind(wx.EVT_BUTTON, self.on_certificacao)
    import subprocess
    def on_pre_report(self, event):
        # Run the escript.exe file
        subprocess.run(["C:\\geoprocessamento\\geo_v1\\geoprocessamento.bat"])


    def on_laudo(self, event):
        # Run the escript.exe file
        subprocess.run(["C:\geoprocessamento\organizar laudo\organizar laudo.exe"])

    def on_certificacao(self, event):
        # Run the escript.exe file
        subprocess.run(["C:\geoprocessamento\certificação_v1\certificação_v1.exe"])

class MyApp(wx.App):
    def OnInit(self):
        self.frame = MyFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
